nohup python python_script/tex_to_xml/run_tex_to_xml.py --root /nvme/zhangtianning/datasets/whole_arxiv_data/whole_arxiv_all_files/unprocessed_tex/2308.07124/octopack.tex --redo > log.log&
nohup python python_script/tex_to_xml/run_tex_to_xml.py --root /nvme/zhangtianning/datasets/whole_arxiv_data/whole_arxiv_all_files/unprocessed_tex/2308.02961/censoredgaming.tex --redo > log.log&
nohup python python_script/tex_to_xml/run_tex_to_xml.py --root /nvme/zhangtianning/datasets/whole_arxiv_data/whole_arxiv_all_files/unprocessed_tex/2309.13060/sn-article.tex --redo > log.log&
nohup python python_script/tex_to_xml/run_tex_to_xml.py --root /nvme/zhangtianning/datasets/whole_arxiv_data/whole_arxiv_all_files/unprocessed_tex/2306.08971/main.tex --redo > log.log&
nohup python python_script/tex_to_xml/run_tex_to_xml.py --root /nvme/zhangtianning/datasets/whole_arxiv_data/whole_arxiv_all_files/unprocessed_tex/2309.13777/main.tex --redo > log.log&
nohup python python_script/tex_to_xml/run_tex_to_xml.py --root /nvme/zhangtianning/datasets/whole_arxiv_data/whole_arxiv_all_files/unprocessed_tex/2309.12980/main_arxiv.tex --redo > log.log&
nohup python python_script/tex_to_xml/run_tex_to_xml.py --root /nvme/zhangtianning/datasets/whole_arxiv_data/whole_arxiv_all_files/unprocessed_tex/1806.10627/Shubina_5.02.23.tex --redo > log.log&
nohup python python_script/tex_to_xml/run_tex_to_xml.py --root /nvme/zhangtianning/datasets/whole_arxiv_data/whole_arxiv_all_files/unprocessed_tex/1312.5627/1312.5627.tex --redo > log.log&
nohup python python_script/tex_to_xml/run_tex_to_xml.py --root /nvme/zhangtianning/datasets/whole_arxiv_data/whole_arxiv_all_files/unprocessed_tex/2308.03429/paper.tex --redo > log.log&
nohup python python_script/tex_to_xml/run_tex_to_xml.py --root /nvme/zhangtianning/datasets/whole_arxiv_data/whole_arxiv_all_files/unprocessed_tex/2308.04030/main.tex --redo > log.log&
nohup python python_script/tex_to_xml/run_tex_to_xml.py --root /nvme/zhangtianning/datasets/whole_arxiv_data/whole_arxiv_all_files/unprocessed_tex/2308.02764/dataopsy.tex --redo > log.log&
nohup python python_script/tex_to_xml/run_tex_to_xml.py --root /nvme/zhangtianning/datasets/whole_arxiv_data/whole_arxiv_all_files/unprocessed_tex/2309.12686/main.tex --redo > log.log&
nohup python python_script/tex_to_xml/run_tex_to_xml.py --root /nvme/zhangtianning/datasets/whole_arxiv_data/whole_arxiv_all_files/unprocessed_tex/2309.13003/main.tex --redo > log.log&
nohup python python_script/tex_to_xml/run_tex_to_xml.py --root /nvme/zhangtianning/datasets/whole_arxiv_data/whole_arxiv_all_files/unprocessed_tex/2309.16575/acl2023.tex --redo > log.log&
nohup python python_script/tex_to_xml/run_tex_to_xml.py --root /nvme/zhangtianning/datasets/whole_arxiv_data/whole_arxiv_all_files/unprocessed_tex/2308.07638/ase23.tex --redo > log.log&
nohup python python_script/tex_to_xml/run_tex_to_xml.py --root /nvme/zhangtianning/datasets/whole_arxiv_data/whole_arxiv_all_files/unprocessed_tex/2308.04380/fne.tex --redo > log.log&
nohup python python_script/tex_to_xml/run_tex_to_xml.py --root /nvme/zhangtianning/datasets/whole_arxiv_data/whole_arxiv_all_files/unprocessed_tex/2306.16147/uncompressed_file.tex --redo > log.log&
nohup python python_script/tex_to_xml/run_tex_to_xml.py --root /nvme/zhangtianning/datasets/whole_arxiv_data/whole_arxiv_all_files/unprocessed_tex/2309.16490/conference_101719.tex --redo > log.log&
nohup python python_script/tex_to_xml/run_tex_to_xml.py --root /nvme/zhangtianning/datasets/whole_arxiv_data/whole_arxiv_all_files/unprocessed_tex/2308.06658/root.tex --redo > log.log&
nohup python python_script/tex_to_xml/run_tex_to_xml.py --root /nvme/zhangtianning/datasets/whole_arxiv_data/whole_arxiv_all_files/unprocessed_tex/2308.07966/main.tex --redo > log.log&
nohup python python_script/tex_to_xml/run_tex_to_xml.py --root /nvme/zhangtianning/datasets/whole_arxiv_data/whole_arxiv_all_files/unprocessed_tex/2309.15378/root.tex --redo > log.log&
nohup python python_script/tex_to_xml/run_tex_to_xml.py --root /nvme/zhangtianning/datasets/whole_arxiv_data/whole_arxiv_all_files/unprocessed_tex/2309.16121/bh1.tex --redo > log.log&
nohup python python_script/tex_to_xml/run_tex_to_xml.py --root /nvme/zhangtianning/datasets/whole_arxiv_data/whole_arxiv_all_files/unprocessed_tex/2309.15374/bare_jrnl.tex --redo > log.log&
nohup python python_script/tex_to_xml/run_tex_to_xml.py --root /nvme/zhangtianning/datasets/whole_arxiv_data/whole_arxiv_all_files/unprocessed_tex/2309.13831/main_text.tex --redo > log.log&
nohup python python_script/tex_to_xml/run_tex_to_xml.py --root /nvme/zhangtianning/datasets/whole_arxiv_data/whole_arxiv_all_files/unprocessed_tex/2309.13315/BigAI.tex --redo > log.log&
nohup python python_script/tex_to_xml/run_tex_to_xml.py --root /nvme/zhangtianning/datasets/whole_arxiv_data/whole_arxiv_all_files/unprocessed_tex/2309.14965/gw_grb.tex --redo > log.log&
nohup python python_script/tex_to_xml/run_tex_to_xml.py --root /nvme/zhangtianning/datasets/whole_arxiv_data/whole_arxiv_all_files/unprocessed_tex/2308.01857/ISEDA-iEDA.tex --redo > log.log&
nohup python python_script/tex_to_xml/run_tex_to_xml.py --root /nvme/zhangtianning/datasets/whole_arxiv_data/whole_arxiv_all_files/unprocessed_tex/2308.06201/main.tex --redo > log.log&
nohup python python_script/tex_to_xml/run_tex_to_xml.py --root /nvme/zhangtianning/datasets/whole_arxiv_data/whole_arxiv_all_files/unprocessed_tex/2309.15847/ltexpprt_doublecolumn.tex --redo > log.log&
nohup python python_script/tex_to_xml/run_tex_to_xml.py --root /nvme/zhangtianning/datasets/whole_arxiv_data/whole_arxiv_all_files/unprocessed_tex/2308.04995/main.tex --redo > log.log&
nohup python python_script/tex_to_xml/run_tex_to_xml.py --root /nvme/zhangtianning/datasets/whole_arxiv_data/whole_arxiv_all_files/unprocessed_tex/2308.09976/cas-sc-template-new.tex --redo > log.log&
nohup python python_script/tex_to_xml/run_tex_to_xml.py --root /nvme/zhangtianning/datasets/whole_arxiv_data/whole_arxiv_all_files/unprocessed_tex/2306.01488/uncompressed_file.tex --redo > log.log&
nohup python python_script/tex_to_xml/run_tex_to_xml.py --root /nvme/zhangtianning/datasets/whole_arxiv_data/whole_arxiv_all_files/unprocessed_tex/2309.16345/pre-print.paper.tex --redo > log.log&
nohup python python_script/tex_to_xml/run_tex_to_xml.py --root /nvme/zhangtianning/datasets/whole_arxiv_data/whole_arxiv_all_files/unprocessed_tex/2309.14841/main.tex --redo > log.log&
nohup python python_script/tex_to_xml/run_tex_to_xml.py --root /nvme/zhangtianning/datasets/whole_arxiv_data/whole_arxiv_all_files/unprocessed_tex/2308.08484/paper.tex --redo > log.log&
nohup python python_script/tex_to_xml/run_tex_to_xml.py --root /nvme/zhangtianning/datasets/whole_arxiv_data/whole_arxiv_all_files/unprocessed_tex/2308.07092/camera_ready_v1.tex --redo > log.log&
nohup python python_script/tex_to_xml/run_tex_to_xml.py --root /nvme/zhangtianning/datasets/whole_arxiv_data/whole_arxiv_all_files/unprocessed_tex/2308.02339/root.tex --redo > log.log&
nohup python python_script/tex_to_xml/run_tex_to_xml.py --root /nvme/zhangtianning/datasets/whole_arxiv_data/whole_arxiv_all_files/unprocessed_tex/2309.14809/main.tex --redo > log.log&
nohup python python_script/tex_to_xml/run_tex_to_xml.py --root /nvme/zhangtianning/datasets/whole_arxiv_data/whole_arxiv_all_files/unprocessed_tex/2309.12492/main.tex --redo > log.log&
nohup python python_script/tex_to_xml/run_tex_to_xml.py --root /nvme/zhangtianning/datasets/whole_arxiv_data/whole_arxiv_all_files/unprocessed_tex/2308.11601/perceptive_router_main.tex --redo > log.log&
